apiVersion: v1
kind: Service
metadata:
  name: {{ name }}
  namespace: {{ namespace }}
  labels:
    app: {{ name }}
spec:
  type: NodePort
  selector:
    app: app-mbsd
  ports:
    - port: {{ port }}
      targetPort:  {{ port }}
